title: linux.code.hacks.gamedev
email: linus.probert@gmail.com
theme: jekyll-theme-hacker
description: > # this means to ignore newlines until "baseurl:"
    // So far, so little
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://liquidityc.github.io" # the base hostname & protocol for your site
twitter_username: LiquidityC
github_username:  LiquidityC

# Build settings
markdown: kramdown
